# After a release is successfully published, upload cargodisttest-example.txt
name: AppendRelease

# We're going to edit a gh release, so we need that permission
permissions:
  contents: write

on:
  # Whenever a workflow called "Release" completes, run this!
  workflow_run:
    workflows: ["Release"]
    types:
        - completed

# Alright, let's do it!
jobs:
  # upload the example
  example:
    name: Add example to release
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Setup
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0
      # We get the tag of the release in github.event.workflow_run.head_branch
      # No idea why it's stored there with that name, but, it is?
      - name: Install oranda and upload schema
        run: |
          echo "uploading schema to ${{ github.event.workflow_run.head_branch }}"
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/Gankra/cargodisttest/releases/download/${{ github.event.workflow_run.head_branch }}/cargodisttest-installer.sh | sh
          cargodisttest "hello" > cargodisttest-example.txt 
          gh release upload ${{ github.event.workflow_run.head_branch }} cargodisttest-example.txt
