name: PublishRelease

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  # This is a bit convoluted so that the other parts of this workflow remain
  # the same even if the way the tag is defined is more complicated
  download-tag:
    runs-on: ubuntu-latest
    outputs:
        tag: ${{ steps.print-tag.outputs.tag }}
    steps:
      - id: print-tag
        run: echo "tag=${{ inputs.tag }}" >> "$GITHUB_OUTPUT"

  # Publish the npm package we uploaded to the github release
  npm-publish:
    runs-on: ubuntu-latest
    needs: download-tag
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          ref: ${{needs.download-tag.outputs.tag}}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm
      - run: npm publish --access public https://github.com/Gankra/cargodisttest/releases/download/${{needs.download-tag.outputs.tag}}/cargodisttest-npm-package.tar.gz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # publish the current repo state to crates.io
  cargo-publish:
    runs-on: ubuntu-latest
    needs: download-tag
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          ref: ${{needs.download-tag.outputs.tag}}
          fetch-depth: 0
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}



      





