name: Web

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '11 7 * * 1,4'

jobs:
  web:
    name: Build and deploy site and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install mdbook
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Run mdbook build
        run: |
          mdbook build docs
      - name: Install and run oranda
        run: |
          cargo install oranda --locked --profile=dist --git=https://github.com/axodotdev/oranda
          oranda build
      - name: Deploy oranda
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages
          folder: public
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
